version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: empay_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: empay
      POSTGRES_PASSWORD: empay123
      POSTGRES_DB: empay_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/sql/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql

volumes:
  pgdata:
